# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArkScanMainWindow.ui'
#
# Created: Sun Mar  1 17:53:45 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ArkScanMainWindow(object):
    def setupUi(self, ArkScanMainWindow):
        ArkScanMainWindow.setObjectName(_fromUtf8("ArkScanMainWindow"))
        ArkScanMainWindow.resize(1092, 1008)
        self.centralwidget = QtGui.QWidget(ArkScanMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.m_resolutionCombo = QtGui.QComboBox(self.groupBox)
        self.m_resolutionCombo.setObjectName(_fromUtf8("m_resolutionCombo"))
        self.m_resolutionCombo.addItem(_fromUtf8(""))
        self.m_resolutionCombo.addItem(_fromUtf8(""))
        self.m_resolutionCombo.addItem(_fromUtf8(""))
        self.m_resolutionCombo.addItem(_fromUtf8(""))
        self.m_resolutionCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.m_resolutionCombo, 1, 1, 1, 1)
        self.m_orientationCombo = QtGui.QComboBox(self.groupBox)
        self.m_orientationCombo.setObjectName(_fromUtf8("m_orientationCombo"))
        self.m_orientationCombo.addItem(_fromUtf8(""))
        self.m_orientationCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.m_orientationCombo, 3, 1, 1, 1)
        self.m_orientationLabel = QtGui.QLabel(self.groupBox)
        self.m_orientationLabel.setObjectName(_fromUtf8("m_orientationLabel"))
        self.gridLayout_2.addWidget(self.m_orientationLabel, 3, 0, 1, 1)
        self.m_pageSizeCombo = QtGui.QComboBox(self.groupBox)
        self.m_pageSizeCombo.setObjectName(_fromUtf8("m_pageSizeCombo"))
        self.m_pageSizeCombo.addItem(_fromUtf8(""))
        self.m_pageSizeCombo.addItem(_fromUtf8(""))
        self.m_pageSizeCombo.addItem(_fromUtf8(""))
        self.m_pageSizeCombo.addItem(_fromUtf8(""))
        self.m_pageSizeCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.m_pageSizeCombo, 2, 1, 1, 1)
        self.m_pageSizeLabel = QtGui.QLabel(self.groupBox)
        self.m_pageSizeLabel.setObjectName(_fromUtf8("m_pageSizeLabel"))
        self.gridLayout_2.addWidget(self.m_pageSizeLabel, 2, 0, 1, 1)
        self.m_resolutionLabel = QtGui.QLabel(self.groupBox)
        self.m_resolutionLabel.setObjectName(_fromUtf8("m_resolutionLabel"))
        self.gridLayout_2.addWidget(self.m_resolutionLabel, 1, 0, 1, 1)
        self.m_modeCombo = QtGui.QComboBox(self.groupBox)
        self.m_modeCombo.setObjectName(_fromUtf8("m_modeCombo"))
        self.m_modeCombo.addItem(_fromUtf8(""))
        self.m_modeCombo.addItem(_fromUtf8(""))
        self.m_modeCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.m_modeCombo, 0, 1, 1, 1)
        self.m_modeLabel = QtGui.QLabel(self.groupBox)
        self.m_modeLabel.setObjectName(_fromUtf8("m_modeLabel"))
        self.gridLayout_2.addWidget(self.m_modeLabel, 0, 0, 1, 1)
        self.m_scanSizeLayout = QtGui.QGridLayout()
        self.m_scanSizeLayout.setObjectName(_fromUtf8("m_scanSizeLayout"))
        self.m_xOriginLabel = QtGui.QLabel(self.groupBox)
        self.m_xOriginLabel.setObjectName(_fromUtf8("m_xOriginLabel"))
        self.m_scanSizeLayout.addWidget(self.m_xOriginLabel, 1, 0, 1, 1)
        self.m_xOriginSpin = QtGui.QSpinBox(self.groupBox)
        self.m_xOriginSpin.setMaximum(297)
        self.m_xOriginSpin.setObjectName(_fromUtf8("m_xOriginSpin"))
        self.m_scanSizeLayout.addWidget(self.m_xOriginSpin, 1, 1, 1, 1)
        self.m_yOriginLabel = QtGui.QLabel(self.groupBox)
        self.m_yOriginLabel.setObjectName(_fromUtf8("m_yOriginLabel"))
        self.m_scanSizeLayout.addWidget(self.m_yOriginLabel, 1, 2, 1, 1)
        self.m_yOriginSpin = QtGui.QSpinBox(self.groupBox)
        self.m_yOriginSpin.setMaximum(433)
        self.m_yOriginSpin.setObjectName(_fromUtf8("m_yOriginSpin"))
        self.m_scanSizeLayout.addWidget(self.m_yOriginSpin, 1, 3, 1, 1)
        self.m_widthLabel = QtGui.QLabel(self.groupBox)
        self.m_widthLabel.setObjectName(_fromUtf8("m_widthLabel"))
        self.m_scanSizeLayout.addWidget(self.m_widthLabel, 2, 0, 1, 1)
        self.m_widthSpin = QtGui.QSpinBox(self.groupBox)
        self.m_widthSpin.setMaximum(297)
        self.m_widthSpin.setObjectName(_fromUtf8("m_widthSpin"))
        self.m_scanSizeLayout.addWidget(self.m_widthSpin, 2, 1, 1, 1)
        self.m_heightLabel = QtGui.QLabel(self.groupBox)
        self.m_heightLabel.setObjectName(_fromUtf8("m_heightLabel"))
        self.m_scanSizeLayout.addWidget(self.m_heightLabel, 2, 2, 1, 1)
        self.m_heightSpin = QtGui.QSpinBox(self.groupBox)
        self.m_heightSpin.setMaximum(433)
        self.m_heightSpin.setObjectName(_fromUtf8("m_heightSpin"))
        self.m_scanSizeLayout.addWidget(self.m_heightSpin, 2, 3, 1, 1)
        self.m_scanSizeLabel1 = QtGui.QLabel(self.groupBox)
        self.m_scanSizeLabel1.setObjectName(_fromUtf8("m_scanSizeLabel1"))
        self.m_scanSizeLayout.addWidget(self.m_scanSizeLabel1, 0, 1, 1, 1)
        self.m_scanSizeLabel2 = QtGui.QLabel(self.groupBox)
        self.m_scanSizeLabel2.setObjectName(_fromUtf8("m_scanSizeLabel2"))
        self.m_scanSizeLayout.addWidget(self.m_scanSizeLabel2, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.m_scanSizeLayout, 4, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox1 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.m_typeLabel = QtGui.QLabel(self.groupBox1)
        self.m_typeLabel.setObjectName(_fromUtf8("m_typeLabel"))
        self.gridLayout_3.addWidget(self.m_typeLabel, 1, 0, 1, 1)
        self.m_numberLabel = QtGui.QLabel(self.groupBox1)
        self.m_numberLabel.setObjectName(_fromUtf8("m_numberLabel"))
        self.gridLayout_3.addWidget(self.m_numberLabel, 2, 0, 1, 1)
        self.m_typeCombo = QtGui.QComboBox(self.groupBox1)
        self.m_typeCombo.setObjectName(_fromUtf8("m_typeCombo"))
        self.m_typeCombo.addItem(_fromUtf8(""))
        self.m_typeCombo.addItem(_fromUtf8(""))
        self.m_typeCombo.addItem(_fromUtf8(""))
        self.m_typeCombo.addItem(_fromUtf8(""))
        self.m_typeCombo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.m_typeCombo, 1, 1, 1, 1)
        self.m_siteLabel = QtGui.QLabel(self.groupBox1)
        self.m_siteLabel.setObjectName(_fromUtf8("m_siteLabel"))
        self.gridLayout_3.addWidget(self.m_siteLabel, 0, 0, 1, 1)
        self.m_numberSpin = QtGui.QSpinBox(self.groupBox1)
        self.m_numberSpin.setMaximum(9999)
        self.m_numberSpin.setObjectName(_fromUtf8("m_numberSpin"))
        self.gridLayout_3.addWidget(self.m_numberSpin, 2, 1, 1, 1)
        self.m_siteEdit = QtGui.QLineEdit(self.groupBox1)
        self.m_siteEdit.setReadOnly(False)
        self.m_siteEdit.setObjectName(_fromUtf8("m_siteEdit"))
        self.gridLayout_3.addWidget(self.m_siteEdit, 0, 1, 1, 1)
        self.m_gridLabel = QtGui.QLabel(self.groupBox1)
        self.m_gridLabel.setObjectName(_fromUtf8("m_gridLabel"))
        self.gridLayout_3.addWidget(self.m_gridLabel, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.m_eastSpin = QtGui.QSpinBox(self.groupBox1)
        self.m_eastSpin.setMaximum(9999)
        self.m_eastSpin.setSingleStep(5)
        self.m_eastSpin.setObjectName(_fromUtf8("m_eastSpin"))
        self.horizontalLayout_2.addWidget(self.m_eastSpin)
        self.m_northSpin = QtGui.QSpinBox(self.groupBox1)
        self.m_northSpin.setMaximum(9999)
        self.m_northSpin.setSingleStep(5)
        self.m_northSpin.setObjectName(_fromUtf8("m_northSpin"))
        self.horizontalLayout_2.addWidget(self.m_northSpin)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.m_suffixLabel = QtGui.QLabel(self.groupBox1)
        self.m_suffixLabel.setObjectName(_fromUtf8("m_suffixLabel"))
        self.gridLayout_3.addWidget(self.m_suffixLabel, 4, 0, 1, 1)
        self.m_suffixEdit = QtGui.QLineEdit(self.groupBox1)
        self.m_suffixEdit.setMaxLength(10)
        self.m_suffixEdit.setObjectName(_fromUtf8("m_suffixEdit"))
        self.gridLayout_3.addWidget(self.m_suffixEdit, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.m_scanSavePlanButton = QtGui.QPushButton(self.groupBox1)
        self.m_scanSavePlanButton.setDefault(True)
        self.m_scanSavePlanButton.setObjectName(_fromUtf8("m_scanSavePlanButton"))
        self.horizontalLayout_3.addWidget(self.m_scanSavePlanButton)
        self.pushButton = QtGui.QPushButton(self.groupBox1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox1)
        self.groupBox2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox2.setObjectName(_fromUtf8("groupBox2"))
        self.m_cropSizeLayout = QtGui.QGridLayout(self.groupBox2)
        self.m_cropSizeLayout.setObjectName(_fromUtf8("m_cropSizeLayout"))
        self.m_hCropLabel = QtGui.QLabel(self.groupBox2)
        self.m_hCropLabel.setObjectName(_fromUtf8("m_hCropLabel"))
        self.m_cropSizeLayout.addWidget(self.m_hCropLabel, 2, 2, 1, 1)
        self.m_hCropSpin = QtGui.QSpinBox(self.groupBox2)
        self.m_hCropSpin.setMaximum(99999)
        self.m_hCropSpin.setObjectName(_fromUtf8("m_hCropSpin"))
        self.m_cropSizeLayout.addWidget(self.m_hCropSpin, 2, 3, 1, 1)
        self.m_pixelLabel1 = QtGui.QLabel(self.groupBox2)
        self.m_pixelLabel1.setObjectName(_fromUtf8("m_pixelLabel1"))
        self.m_cropSizeLayout.addWidget(self.m_pixelLabel1, 0, 1, 1, 1)
        self.m_pixelLabel2 = QtGui.QLabel(self.groupBox2)
        self.m_pixelLabel2.setObjectName(_fromUtf8("m_pixelLabel2"))
        self.m_cropSizeLayout.addWidget(self.m_pixelLabel2, 0, 3, 1, 1)
        self.m_xCropLabel = QtGui.QLabel(self.groupBox2)
        self.m_xCropLabel.setObjectName(_fromUtf8("m_xCropLabel"))
        self.m_cropSizeLayout.addWidget(self.m_xCropLabel, 1, 0, 1, 1)
        self.m_xCropSpin = QtGui.QSpinBox(self.groupBox2)
        self.m_xCropSpin.setMaximum(99999)
        self.m_xCropSpin.setObjectName(_fromUtf8("m_xCropSpin"))
        self.m_cropSizeLayout.addWidget(self.m_xCropSpin, 1, 1, 1, 1)
        self.m_yCropLabel = QtGui.QLabel(self.groupBox2)
        self.m_yCropLabel.setObjectName(_fromUtf8("m_yCropLabel"))
        self.m_cropSizeLayout.addWidget(self.m_yCropLabel, 1, 2, 1, 1)
        self.m_yCropSpin = QtGui.QSpinBox(self.groupBox2)
        self.m_yCropSpin.setMaximum(99999)
        self.m_yCropSpin.setObjectName(_fromUtf8("m_yCropSpin"))
        self.m_cropSizeLayout.addWidget(self.m_yCropSpin, 1, 3, 1, 1)
        self.m_wCropLabel = QtGui.QLabel(self.groupBox2)
        self.m_wCropLabel.setObjectName(_fromUtf8("m_wCropLabel"))
        self.m_cropSizeLayout.addWidget(self.m_wCropLabel, 2, 0, 1, 1)
        self.m_wCropSpin = QtGui.QSpinBox(self.groupBox2)
        self.m_wCropSpin.setMaximum(99999)
        self.m_wCropSpin.setObjectName(_fromUtf8("m_wCropSpin"))
        self.m_cropSizeLayout.addWidget(self.m_wCropSpin, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.m_detectCropAreaButton = QtGui.QPushButton(self.groupBox2)
        self.m_detectCropAreaButton.setObjectName(_fromUtf8("m_detectCropAreaButton"))
        self.horizontalLayout.addWidget(self.m_detectCropAreaButton)
        self.m_cropButton = QtGui.QPushButton(self.groupBox2)
        self.m_cropButton.setObjectName(_fromUtf8("m_cropButton"))
        self.horizontalLayout.addWidget(self.m_cropButton)
        self.m_cropSizeLayout.addLayout(self.horizontalLayout, 3, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBox2)
        self.m_progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.m_progressBar.setProperty("value", 0)
        self.m_progressBar.setObjectName(_fromUtf8("m_progressBar"))
        self.verticalLayout.addWidget(self.m_progressBar)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.m_scanView = ArkScanGraphicsView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_scanView.sizePolicy().hasHeightForWidth())
        self.m_scanView.setSizePolicy(sizePolicy)
        self.m_scanView.setMinimumSize(QtCore.QSize(800, 400))
        self.m_scanView.setAutoFillBackground(True)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.m_scanView.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.m_scanView.setForegroundBrush(brush)
        self.m_scanView.setInteractive(True)
        self.m_scanView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.m_scanView.setObjectName(_fromUtf8("m_scanView"))
        self.m_outputText = QtGui.QTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_outputText.sizePolicy().hasHeightForWidth())
        self.m_outputText.setSizePolicy(sizePolicy)
        self.m_outputText.setMaximumSize(QtCore.QSize(16777215, 100))
        self.m_outputText.setObjectName(_fromUtf8("m_outputText"))
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        ArkScanMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ArkScanMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.m_menu = QtGui.QMenu(self.menubar)
        self.m_menu.setObjectName(_fromUtf8("m_menu"))
        self.menuScan = QtGui.QMenu(self.menubar)
        self.menuScan.setObjectName(_fromUtf8("menuScan"))
        self.menuPlan = QtGui.QMenu(self.menubar)
        self.menuPlan.setObjectName(_fromUtf8("menuPlan"))
        self.menuCrop = QtGui.QMenu(self.menubar)
        self.menuCrop.setObjectName(_fromUtf8("menuCrop"))
        ArkScanMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ArkScanMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ArkScanMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ArkScanMainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ArkScanMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.quitAction = QtGui.QAction(ArkScanMainWindow)
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.m_previewAction = QtGui.QAction(ArkScanMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/previewIcon/document-preview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_previewAction.setIcon(icon)
        self.m_previewAction.setObjectName(_fromUtf8("m_previewAction"))
        self.m_scanAction = QtGui.QAction(ArkScanMainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/scanIcon/scanner.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_scanAction.setIcon(icon1)
        self.m_scanAction.setObjectName(_fromUtf8("m_scanAction"))
        self.m_printAction = QtGui.QAction(ArkScanMainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/printIcon/document-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_printAction.setIcon(icon2)
        self.m_printAction.setObjectName(_fromUtf8("m_printAction"))
        self.m_saveAction = QtGui.QAction(ArkScanMainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/saveIcon/document-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_saveAction.setIcon(icon3)
        self.m_saveAction.setObjectName(_fromUtf8("m_saveAction"))
        self.m_copyAction = QtGui.QAction(ArkScanMainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/copyIcon/edit-copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_copyAction.setIcon(icon4)
        self.m_copyAction.setObjectName(_fromUtf8("m_copyAction"))
        self.m_scanSavePlanAction = QtGui.QAction(ArkScanMainWindow)
        self.m_scanSavePlanAction.setObjectName(_fromUtf8("m_scanSavePlanAction"))
        self.m_savePlanAction = QtGui.QAction(ArkScanMainWindow)
        self.m_savePlanAction.setIcon(icon3)
        self.m_savePlanAction.setObjectName(_fromUtf8("m_savePlanAction"))
        self.m_scanPlanAction = QtGui.QAction(ArkScanMainWindow)
        self.m_scanPlanAction.setIcon(icon1)
        self.m_scanPlanAction.setObjectName(_fromUtf8("m_scanPlanAction"))
        self.m_scanCropSavePlanAction = QtGui.QAction(ArkScanMainWindow)
        self.m_scanCropSavePlanAction.setObjectName(_fromUtf8("m_scanCropSavePlanAction"))
        self.m_detectCropAreaAction = QtGui.QAction(ArkScanMainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/autoCropIcon/transform-crop-and-resize.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_detectCropAreaAction.setIcon(icon5)
        self.m_detectCropAreaAction.setObjectName(_fromUtf8("m_detectCropAreaAction"))
        self.m_cropAction = QtGui.QAction(ArkScanMainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/cropIcon/transform-crop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m_cropAction.setIcon(icon6)
        self.m_cropAction.setObjectName(_fromUtf8("m_cropAction"))
        self.m_menu.addAction(self.quitAction)
        self.menuScan.addAction(self.m_previewAction)
        self.menuScan.addAction(self.m_scanAction)
        self.menuScan.addAction(self.m_saveAction)
        self.menuScan.addAction(self.m_printAction)
        self.menuScan.addAction(self.m_copyAction)
        self.menuPlan.addAction(self.m_scanPlanAction)
        self.menuPlan.addAction(self.m_savePlanAction)
        self.menuPlan.addAction(self.m_scanSavePlanAction)
        self.menuPlan.addAction(self.m_scanCropSavePlanAction)
        self.menuCrop.addAction(self.m_detectCropAreaAction)
        self.menuCrop.addAction(self.m_cropAction)
        self.menubar.addAction(self.m_menu.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuPlan.menuAction())
        self.menubar.addAction(self.menuCrop.menuAction())
        self.toolBar.addAction(self.m_previewAction)
        self.toolBar.addAction(self.m_scanAction)
        self.toolBar.addAction(self.m_saveAction)
        self.toolBar.addAction(self.m_printAction)
        self.toolBar.addAction(self.m_copyAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.m_scanPlanAction)
        self.toolBar.addAction(self.m_savePlanAction)

        self.retranslateUi(ArkScanMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ArkScanMainWindow)
        ArkScanMainWindow.setTabOrder(self.m_siteEdit, self.m_typeCombo)
        ArkScanMainWindow.setTabOrder(self.m_typeCombo, self.m_numberSpin)
        ArkScanMainWindow.setTabOrder(self.m_numberSpin, self.m_eastSpin)
        ArkScanMainWindow.setTabOrder(self.m_eastSpin, self.m_northSpin)
        ArkScanMainWindow.setTabOrder(self.m_northSpin, self.m_suffixEdit)
        ArkScanMainWindow.setTabOrder(self.m_suffixEdit, self.m_modeCombo)
        ArkScanMainWindow.setTabOrder(self.m_modeCombo, self.m_resolutionCombo)
        ArkScanMainWindow.setTabOrder(self.m_resolutionCombo, self.m_pageSizeCombo)
        ArkScanMainWindow.setTabOrder(self.m_pageSizeCombo, self.m_orientationCombo)
        ArkScanMainWindow.setTabOrder(self.m_orientationCombo, self.m_xOriginSpin)
        ArkScanMainWindow.setTabOrder(self.m_xOriginSpin, self.m_yOriginSpin)
        ArkScanMainWindow.setTabOrder(self.m_yOriginSpin, self.m_widthSpin)
        ArkScanMainWindow.setTabOrder(self.m_widthSpin, self.m_heightSpin)
        ArkScanMainWindow.setTabOrder(self.m_heightSpin, self.m_xCropSpin)
        ArkScanMainWindow.setTabOrder(self.m_xCropSpin, self.m_yCropSpin)
        ArkScanMainWindow.setTabOrder(self.m_yCropSpin, self.m_wCropSpin)
        ArkScanMainWindow.setTabOrder(self.m_wCropSpin, self.m_hCropSpin)
        ArkScanMainWindow.setTabOrder(self.m_hCropSpin, self.m_scanView)
        ArkScanMainWindow.setTabOrder(self.m_scanView, self.m_outputText)

    def retranslateUi(self, ArkScanMainWindow):
        ArkScanMainWindow.setWindowTitle(_translate("ArkScanMainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("ArkScanMainWindow", "Scan Settings", None))
        self.m_resolutionCombo.setItemText(0, _translate("ArkScanMainWindow", "600", None))
        self.m_resolutionCombo.setItemText(1, _translate("ArkScanMainWindow", "300", None))
        self.m_resolutionCombo.setItemText(2, _translate("ArkScanMainWindow", "150", None))
        self.m_resolutionCombo.setItemText(3, _translate("ArkScanMainWindow", "75", None))
        self.m_resolutionCombo.setItemText(4, _translate("ArkScanMainWindow", "50", None))
        self.m_orientationCombo.setItemText(0, _translate("ArkScanMainWindow", "Portrait", None))
        self.m_orientationCombo.setItemText(1, _translate("ArkScanMainWindow", "Landscape", None))
        self.m_orientationLabel.setText(_translate("ArkScanMainWindow", "Orientation", None))
        self.m_pageSizeCombo.setItemText(0, _translate("ArkScanMainWindow", "Permatrace", None))
        self.m_pageSizeCombo.setItemText(1, _translate("ArkScanMainWindow", "A3", None))
        self.m_pageSizeCombo.setItemText(2, _translate("ArkScanMainWindow", "A4", None))
        self.m_pageSizeCombo.setItemText(3, _translate("ArkScanMainWindow", "A5", None))
        self.m_pageSizeCombo.setItemText(4, _translate("ArkScanMainWindow", "Custom", None))
        self.m_pageSizeLabel.setText(_translate("ArkScanMainWindow", "Page Size:", None))
        self.m_resolutionLabel.setText(_translate("ArkScanMainWindow", "Resolution:", None))
        self.m_modeCombo.setItemText(0, _translate("ArkScanMainWindow", "Color", None))
        self.m_modeCombo.setItemText(1, _translate("ArkScanMainWindow", "Grayscale", None))
        self.m_modeCombo.setItemText(2, _translate("ArkScanMainWindow", "Line", None))
        self.m_modeLabel.setText(_translate("ArkScanMainWindow", "Mode:", None))
        self.m_xOriginLabel.setText(_translate("ArkScanMainWindow", "X:", None))
        self.m_yOriginLabel.setText(_translate("ArkScanMainWindow", "Y:", None))
        self.m_widthLabel.setText(_translate("ArkScanMainWindow", "W:", None))
        self.m_heightLabel.setText(_translate("ArkScanMainWindow", "H:", None))
        self.m_scanSizeLabel1.setText(_translate("ArkScanMainWindow", "0mm - 297mm", None))
        self.m_scanSizeLabel2.setText(_translate("ArkScanMainWindow", "0mm - 433mm", None))
        self.groupBox1.setTitle(_translate("ArkScanMainWindow", "Plan Metadata", None))
        self.m_typeLabel.setText(_translate("ArkScanMainWindow", "Type:", None))
        self.m_numberLabel.setText(_translate("ArkScanMainWindow", "Number:", None))
        self.m_typeCombo.setItemText(0, _translate("ArkScanMainWindow", "Context", None))
        self.m_typeCombo.setItemText(1, _translate("ArkScanMainWindow", "Plan", None))
        self.m_typeCombo.setItemText(2, _translate("ArkScanMainWindow", "Section", None))
        self.m_typeCombo.setItemText(3, _translate("ArkScanMainWindow", "Top Plan", None))
        self.m_typeCombo.setItemText(4, _translate("ArkScanMainWindow", "Matrix", None))
        self.m_siteLabel.setText(_translate("ArkScanMainWindow", "Site:", None))
        self.m_numberSpin.setToolTip(_translate("ArkScanMainWindow", "Context Number", None))
        self.m_gridLabel.setText(_translate("ArkScanMainWindow", "Grid Ref:", None))
        self.m_suffixLabel.setText(_translate("ArkScanMainWindow", "Suffix:", None))
        self.m_scanSavePlanButton.setText(_translate("ArkScanMainWindow", "Scan && Save", None))
        self.pushButton.setText(_translate("ArkScanMainWindow", "Save", None))
        self.groupBox2.setTitle(_translate("ArkScanMainWindow", "Crop Settings", None))
        self.m_hCropLabel.setText(_translate("ArkScanMainWindow", "H:", None))
        self.m_pixelLabel1.setText(_translate("ArkScanMainWindow", "Pixels", None))
        self.m_pixelLabel2.setText(_translate("ArkScanMainWindow", "Pixels", None))
        self.m_xCropLabel.setText(_translate("ArkScanMainWindow", "X:", None))
        self.m_yCropLabel.setText(_translate("ArkScanMainWindow", "Y:", None))
        self.m_wCropLabel.setText(_translate("ArkScanMainWindow", "W:", None))
        self.m_detectCropAreaButton.setText(_translate("ArkScanMainWindow", "Detect", None))
        self.m_cropButton.setText(_translate("ArkScanMainWindow", "Crop", None))
        self.m_menu.setTitle(_translate("ArkScanMainWindow", "ArkScan", None))
        self.menuScan.setTitle(_translate("ArkScanMainWindow", "Scan", None))
        self.menuPlan.setTitle(_translate("ArkScanMainWindow", "Plan", None))
        self.menuCrop.setTitle(_translate("ArkScanMainWindow", "Crop", None))
        self.toolBar.setWindowTitle(_translate("ArkScanMainWindow", "toolBar", None))
        self.quitAction.setText(_translate("ArkScanMainWindow", "Quit", None))
        self.m_previewAction.setText(_translate("ArkScanMainWindow", "P&review", None))
        self.m_scanAction.setText(_translate("ArkScanMainWindow", "Sca&n", None))
        self.m_printAction.setText(_translate("ArkScanMainWindow", "&Print", None))
        self.m_saveAction.setText(_translate("ArkScanMainWindow", "&Save", None))
        self.m_copyAction.setText(_translate("ArkScanMainWindow", "&Copy", None))
        self.m_scanSavePlanAction.setText(_translate("ArkScanMainWindow", "Scan && Save", None))
        self.m_savePlanAction.setText(_translate("ArkScanMainWindow", "Save Plan", None))
        self.m_scanPlanAction.setText(_translate("ArkScanMainWindow", "Scan Plan", None))
        self.m_scanCropSavePlanAction.setText(_translate("ArkScanMainWindow", "Scan, Crop, && Save", None))
        self.m_detectCropAreaAction.setText(_translate("ArkScanMainWindow", "DetectCrop Area", None))
        self.m_cropAction.setText(_translate("ArkScanMainWindow", "Crop", None))

from ark_scan_graphics_view import ArkScanGraphicsView
import resources_rc
