# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArkScanMainWindow.ui'
#
# Created: Tue Jan 20 15:37:43 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ArkScanMainWindow(object):
    def setupUi(self, ArkScanMainWindow):
        ArkScanMainWindow.setObjectName(_fromUtf8("ArkScanMainWindow"))
        ArkScanMainWindow.resize(656, 533)
        self.centralwidget = QtGui.QWidget(ArkScanMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.m_siteLabel = QtGui.QLabel(self.widget)
        self.m_siteLabel.setObjectName(_fromUtf8("m_siteLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.m_siteLabel)
        self.m_siteEdit = QtGui.QLineEdit(self.widget)
        self.m_siteEdit.setReadOnly(True)
        self.m_siteEdit.setObjectName(_fromUtf8("m_siteEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.m_siteEdit)
        self.m_gridLabel = QtGui.QLabel(self.widget)
        self.m_gridLabel.setObjectName(_fromUtf8("m_gridLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.m_gridLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.m_eastSpin = QtGui.QSpinBox(self.widget)
        self.m_eastSpin.setMaximum(9999)
        self.m_eastSpin.setObjectName(_fromUtf8("m_eastSpin"))
        self.horizontalLayout_2.addWidget(self.m_eastSpin)
        self.m_northSpin = QtGui.QSpinBox(self.widget)
        self.m_northSpin.setMaximum(9999)
        self.m_northSpin.setObjectName(_fromUtf8("m_northSpin"))
        self.horizontalLayout_2.addWidget(self.m_northSpin)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.m_contextLabel = QtGui.QLabel(self.widget)
        self.m_contextLabel.setObjectName(_fromUtf8("m_contextLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.m_contextLabel)
        self.m_contextSpin = QtGui.QSpinBox(self.widget)
        self.m_contextSpin.setMaximum(9999)
        self.m_contextSpin.setObjectName(_fromUtf8("m_contextSpin"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.m_contextSpin)
        self.verticalLayout.addLayout(self.formLayout)
        self.m_previewButton = QtGui.QPushButton(self.widget)
        self.m_previewButton.setObjectName(_fromUtf8("m_previewButton"))
        self.verticalLayout.addWidget(self.m_previewButton)
        self.m_defaultButton = QtGui.QPushButton(self.widget)
        self.m_defaultButton.setObjectName(_fromUtf8("m_defaultButton"))
        self.verticalLayout.addWidget(self.m_defaultButton)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.m_xLabel = QtGui.QLabel(self.widget)
        self.m_xLabel.setObjectName(_fromUtf8("m_xLabel"))
        self.gridLayout.addWidget(self.m_xLabel, 0, 0, 1, 1)
        self.m_xSpin = QtGui.QSpinBox(self.widget)
        self.m_xSpin.setObjectName(_fromUtf8("m_xSpin"))
        self.gridLayout.addWidget(self.m_xSpin, 0, 1, 1, 1)
        self.m_yLabel = QtGui.QLabel(self.widget)
        self.m_yLabel.setObjectName(_fromUtf8("m_yLabel"))
        self.gridLayout.addWidget(self.m_yLabel, 0, 2, 1, 1)
        self.m_ySpin = QtGui.QSpinBox(self.widget)
        self.m_ySpin.setObjectName(_fromUtf8("m_ySpin"))
        self.gridLayout.addWidget(self.m_ySpin, 0, 3, 1, 1)
        self.m_wLabel = QtGui.QLabel(self.widget)
        self.m_wLabel.setObjectName(_fromUtf8("m_wLabel"))
        self.gridLayout.addWidget(self.m_wLabel, 1, 0, 1, 1)
        self.m_wSpin = QtGui.QSpinBox(self.widget)
        self.m_wSpin.setObjectName(_fromUtf8("m_wSpin"))
        self.gridLayout.addWidget(self.m_wSpin, 1, 1, 1, 1)
        self.m_hLabel = QtGui.QLabel(self.widget)
        self.m_hLabel.setObjectName(_fromUtf8("m_hLabel"))
        self.gridLayout.addWidget(self.m_hLabel, 1, 2, 1, 1)
        self.m_hSpin = QtGui.QSpinBox(self.widget)
        self.m_hSpin.setObjectName(_fromUtf8("m_hSpin"))
        self.gridLayout.addWidget(self.m_hSpin, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.m_scanButton = QtGui.QPushButton(self.widget)
        self.m_scanButton.setObjectName(_fromUtf8("m_scanButton"))
        self.verticalLayout.addWidget(self.m_scanButton)
        self.m_autocropButton = QtGui.QPushButton(self.widget)
        self.m_autocropButton.setObjectName(_fromUtf8("m_autocropButton"))
        self.verticalLayout.addWidget(self.m_autocropButton)
        self.m_autoscanButton = QtGui.QPushButton(self.widget)
        self.m_autoscanButton.setObjectName(_fromUtf8("m_autoscanButton"))
        self.verticalLayout.addWidget(self.m_autoscanButton)
        self.m_progressBar = QtGui.QProgressBar(self.widget)
        self.m_progressBar.setProperty("value", 0)
        self.m_progressBar.setObjectName(_fromUtf8("m_progressBar"))
        self.verticalLayout.addWidget(self.m_progressBar)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.m_scanView = QtGui.QGraphicsView(self.splitter)
        self.m_scanView.setObjectName(_fromUtf8("m_scanView"))
        self.m_outputText = QtGui.QTextBrowser(self.splitter)
        self.m_outputText.setObjectName(_fromUtf8("m_outputText"))
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        ArkScanMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ArkScanMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.m_menu = QtGui.QMenu(self.menubar)
        self.m_menu.setObjectName(_fromUtf8("m_menu"))
        ArkScanMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ArkScanMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ArkScanMainWindow.setStatusBar(self.statusbar)
        self.m_quitAction = QtGui.QAction(ArkScanMainWindow)
        self.m_quitAction.setObjectName(_fromUtf8("m_quitAction"))
        self.m_menu.addAction(self.m_quitAction)
        self.menubar.addAction(self.m_menu.menuAction())
        self.m_siteLabel.setBuddy(self.m_siteEdit)
        self.m_gridLabel.setBuddy(self.m_eastSpin)
        self.m_contextLabel.setBuddy(self.m_contextSpin)

        self.retranslateUi(ArkScanMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ArkScanMainWindow)

    def retranslateUi(self, ArkScanMainWindow):
        ArkScanMainWindow.setWindowTitle(_translate("ArkScanMainWindow", "MainWindow", None))
        self.m_siteLabel.setText(_translate("ArkScanMainWindow", "Site:", None))
        self.m_gridLabel.setText(_translate("ArkScanMainWindow", "Grid Ref:", None))
        self.m_contextLabel.setText(_translate("ArkScanMainWindow", "Context:", None))
        self.m_contextSpin.setToolTip(_translate("ArkScanMainWindow", "Context Number", None))
        self.m_previewButton.setText(_translate("ArkScanMainWindow", "Preview", None))
        self.m_defaultButton.setText(_translate("ArkScanMainWindow", "Default", None))
        self.m_xLabel.setText(_translate("ArkScanMainWindow", "X:", None))
        self.m_yLabel.setText(_translate("ArkScanMainWindow", "Y:", None))
        self.m_wLabel.setText(_translate("ArkScanMainWindow", "W:", None))
        self.m_hLabel.setText(_translate("ArkScanMainWindow", "H:", None))
        self.m_scanButton.setText(_translate("ArkScanMainWindow", "Scan", None))
        self.m_autocropButton.setText(_translate("ArkScanMainWindow", "Auto Crop", None))
        self.m_autoscanButton.setText(_translate("ArkScanMainWindow", "Scan and AutoCrop", None))
        self.m_menu.setTitle(_translate("ArkScanMainWindow", "ArkScan", None))
        self.m_quitAction.setText(_translate("ArkScanMainWindow", "Quit", None))

